kind: pipeline
name: default

steps:
  - name: Build
    image: maven:3.8-openjdk-11
    commands:
      - mvn clean install -DskipTests

  - name: Test
    image: maven:3.8-openjdk-11
    commands:
      - mvn test

  - name: Deploy
    image: maven:3.8-openjdk-11
    commands:
      - mvn spring-boot:run
    when:
      branch:
        - main

trigger:
  branch:
    - main
    - develop
